refactor(rest): ensure types follow naming pattern
discordjs/discord-api-types pull request #1065
Opened 2024-08-19 20:35 UTC by almeidx

Added a custom ESLint rule to ensure REST types follow the following naming pattern:

```js
/^REST(?:Get|Patch|Post|Put|Delete)\w+(?:JSONBody|FormDataBody|URLEncodedData|Result|Query)$/
```

2024-08-19 21:52 UTC, vladfrangu commented on .eslint-plugin-local/index.ts
> +					invalidName: '{{ name }} does not match REST type naming convention',
Lets add in the naming convention somehow so users know ahead of time

2024-08-22 11:09 UTC, Syjalo requested changes

2024-08-22 11:09 UTC, Syjalo commented on .eslint-plugin-local/index.ts
> +	/^REST(?:Get|Patch|Post|Put|Delete)\w+(?:JSONBody|FormDataBody|URLEncodedData|Result|Query)$/;
`\w` includes `_`, which is not allowed in PascalCase
```suggestion
	/^REST(?:Get|Patch|Post|Put|Delete)[a-zA-Z0-9]+(?:JSONBody|FormDataBody|URLEncodedData|Result|Query)$/;
```

2024-08-22 11:41 UTC, vladfrangu approved these changes

2024-08-22 11:41 UTC, merged