fix(APIMessageSnapshot): mark `guild_id` as deprecated
discordjs/discord-api-types pull request #1084
Opened 2024-08-30 21:40 UTC by sdanialraza

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

2024-08-30 21:53 UTC, almeidx approved these changes

2024-08-30 22:01 UTC, Jiralite commented
Do you mind putting a reference in, such as pull request X didn't do something, upstream did something, etc. as it makes investigating in the future more easier!

2024-08-31 00:59 UTC, vladfrangu requested changes

2024-08-31 00:59 UTC, vladfrangu commented on deno/payloads/v10/channel.ts
> +	 * @deprecated This field doesn't accurately reflect the Discord API as it doesn't exist nor is documented.
Please add in what Jira said + that it will be removed in the next major version

2024-08-31 15:51 UTC, almeidx approved these changes

2024-08-31 17:05 UTC, Jiralite approved these changes

2024-09-05 15:25 UTC, merged