refactor: make enum property casing consistent
discordjs/discord-api-types pull request #131
Opened 2021-05-07 17:08 UTC by vaporox

**Please describe the changes this PR makes and why it should be merged:**

This PR converts all enum properties to upper case for more consistency within the library.

2021-05-10 21:09 UTC, vladfrangu requested changes

2021-05-10 21:09 UTC, vladfrangu commented on payloads/v8/channel.ts
> +	UserPremoimGuildSubscriptionTier3,
Bonk

2021-05-10 21:57 UTC, kyranet reviewed
Should `PermissionFlagsBits` be PascalCase as well? It's not an enum, but it behaves similar to one. cc: @vladfrangu 

https://github.com/vaporox/discord-api-types/blob/6dc030fe0cb5f44f15bdb62e738672f5ce50fbab/payloads/v8/permissions.ts#L15-L47

Other than that, there are no more SCREAMING_SNAKE_CASE keys besides v6's values, which are untouched by this PR.

2021-05-11 08:03 UTC, iCrawl approved these changes

2021-05-11 10:14 UTC, vladfrangu commented
> Should `PermissionFlagsBits` be PascalCase as well? It's not an enum, but it behaves similar to one. cc: @vladfrangu
> 
> [vaporox/discord-api-types@`6dc030f`/payloads/v8/permissions.ts#L15-L47](https://github.com/vaporox/discord-api-types/blob/6dc030fe0cb5f44f15bdb62e738672f5ce50fbab/payloads/v8/permissions.ts#L15-L47)
> 
> Other than that, there are no more SCREAMING_SNAKE_CASE keys besides v6's values, which are untouched by this PR.

Yes! @vaporox ^

2021-05-11 13:38 UTC, vaporox commented
Did that (with some unrelated things I found along the way as well), should the v6 types remain untouched?

2021-05-11 15:14 UTC, kyranet requested changes

2021-05-11 15:14 UTC, kyranet commented on deno/gateway/v8.ts
> +export enum GatewayOpcodes {
*OPCode* stands for *OP Code*, which is an abbreviation of *Operation Code*, as such, the enum's name should be OpCode:
```suggestion
export enum GatewayOpCodes {
```

2021-05-11 15:14 UTC, kyranet commented on deno/gateway/v8.ts
> +export enum GatewayOpcodes {
Also rename all references to it.

2021-05-11 20:58 UTC, merged