fix(RESTPutAPIChannelPermissionJSONBody): make properties optional and nullable
discordjs/discord-api-types pull request #141
Opened 2021-06-08 06:59 UTC by cherryblossom000

**Please describe the changes this PR makes and why it should be merged:**

This PR makes `allow`, `deny`, and `type` optional and nullable in `RESTPutAPIChannelPermissionJSONBody`, which is also used in `APIGuildCreateOverwrite`.

**Reference Discord API Docs PRs or commits:** https://github.com/discord/discord-api-docs/pull/3094

2021-06-08 11:15 UTC, vladfrangu requested changes

2021-06-08 11:15 UTC, vladfrangu commented on rest/v8/channel.ts
>  	 * `0` for a role or `1` for a member
Document defaults

2021-06-08 11:30 UTC, cherryblossom000 commented on rest/v8/channel.ts
>  	 * `0` for a role or `1` for a member
I've just added this, thanks.

2021-06-08 11:32 UTC, vladfrangu approved these changes

2021-06-08 18:13 UTC, kyranet approved these changes

2021-06-15 11:56 UTC, iCrawl approved these changes

2021-06-15 12:37 UTC, vladfrangu requested changes
Blocking until resolution from the linked PR

2021-07-18 16:56 UTC, vladfrangu commented
Closing this as it's become stale. If you ever get a response to the linked PR, please re-open this PR! (ping me here and I will reopen it for you)

2021-07-18 16:56 UTC, closed without merging