feat(FormattingPatterns): add timestamp
discordjs/discord-api-types pull request #146
Opened 2021-06-18 04:12 UTC by ckohen

**Please describe the changes this PR makes and why it should be merged:**

Timezone formatted timestamps!!!!! (but the regex matches)

**Reference Discord API Docs PRs or commits:**
https://github.com/discord/discord-api-docs/pull/3135

2021-06-18 05:16 UTC, vladfrangu requested changes

2021-06-18 05:16 UTC, vladfrangu commented on globals.ts
> +	 * The `timetsamp` and `flag` group properties are present on the `exec` result of this expression
Typo'd

2021-06-18 09:41 UTC, kyranet requested changes
Also, should it be named `flag` and not `style` or `pattern`? Is this the name used by Discord?

2021-06-18 09:41 UTC, kyranet commented on globals.ts
> +	 * The `timestamp` and `fllag` group properties are present on the `exec` result of this expression
```suggestion
	 * The `timestamp` and `flag` group properties are present on the `exec` result of this expression
```

2021-06-18 09:42 UTC, advaith1 commented
Discord calls them flags: [docs](https://github.com/discord/discord-api-docs/pull/3135/files?short_path=9c04655#diff-9c0465597400a1bfff16968024a03ed3e42f9f35b43b9d4419bb0156d47ff9d2)

2021-06-18 19:24 UTC, devsnek commented
style would probably be a better name, feel free to change the docs lol

2021-06-18 21:38 UTC, kyranet approved these changes

2021-06-19 18:15 UTC, vladfrangu approved these changes

2021-06-19 18:15 UTC, merged