feat(RESTJSONErrorCodes): add 170007
discordjs/discord-api-types pull request #155
Opened 2021-07-17 00:37 UTC by advaith1

https://github.com/discord/discord-api-docs/pull/3128/commits/a02d435ca278e00ff414a2822eba0e34bdfa736a
- in https://github.com/discord/discord-api-docs/pull/3128

2021-07-17 00:40 UTC, vladfrangu approved these changes

2021-07-19 21:40 UTC, kyranet approved these changes

2021-07-19 22:24 UTC, kyranet commented
Upstream PR has landed, we can merge this now.

2021-07-19 22:27 UTC, vladfrangu requested changes

2021-07-19 22:27 UTC, vladfrangu commented on rest/common.ts
> +	StickerFrameCountExceeds1000Max,
```suggestion
	StickerFrameCountExceedsMaximumOf1000Frames,
```

2021-07-19 22:27 UTC, vladfrangu commented on rest/common.ts
> +	StickerAnimationDurationExceeds5SecondMax,
```suggestion
	StickerAnimationDurationExceedsMaximumOf5Seconds,
```

2021-07-19 22:43 UTC, vladfrangu approved these changes

2021-07-19 22:46 UTC, merged