chore: Get up to date *again*
discordjs/discord-api-types pull request #156
Opened 2021-07-18 15:52 UTC by vladfrangu

**Please describe the changes this PR makes and why it should be merged:**

Draft for now, as I still have lots to do :megu:

**Reference Discord API Docs PRs or commits:**

2021-07-18 17:16 UTC, kyranet approved these changes

2021-07-19 00:47 UTC, monbrey requested changes

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/_interactions/responses.ts
> + * https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionapplicationcommandcallbackdata
```suggestion
 * https://discord.com/developers/docs/interactions/slash-commands#interaction-response-object-interaction-application-command-callback-data-structure
```

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/_interactions/slashCommands.ts
> + * https://discord.com/developers/docs/interactions/slash-commands#applicationcommand
```suggestion
 * https://discord.com/developers/docs/interactions/slash-commands#application-command-object
```

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/_interactions/slashCommands.ts
> +	application_id: Snowflake;
```suggestion
	application_id: Snowflake;
	/**
	 * Guild id of the command, if not global
	 */
	guild_id?: Snowflake;
```
Unsure if this belongs here but it was missing

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/_interactions/slashCommands.ts
> + * https://discord.com/developers/docs/interactions/slash-commands#applicationcommandoption
```suggestion
 * https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-structure
```

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/_interactions/slashCommands.ts
> + * https://discord.com/developers/docs/interactions/slash-commands#applicationcommandoptiontype
```suggestion
 * https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-type
```

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/_interactions/slashCommands.ts
> + * https://discord.com/developers/docs/interactions/slash-commands#applicationcommandoptionchoice
```suggestion
 * https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-choice-structure
```

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/_interactions/slashCommands.ts
> + * https://discord.com/developers/docs/interactions/slash-commands#interaction-applicationcommandinteractiondata
```suggestion
 * https://discord.com/developers/docs/interactions/slash-commands#interaction-object-interaction-structure
```

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/_interactions/slashCommands.ts
> + * https://discord.com/developers/docs/interactions/slash-commands#interaction-applicationcommandinteractiondataoption
```suggestion
 * https://discord.com/developers/docs/interactions/slash-commands#interaction-object-application-command-interaction-data-option-structure
```

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/_interactions/slashCommands.ts
> + * https://discord.com/developers/docs/interactions/slash-commands#guildapplicationcommandpermissions
```suggestion
 * https://discord.com/developers/docs/interactions/slash-commands#application-command-permissions-object-guild-application-command-permissions-structure
```

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/_interactions/slashCommands.ts
> + * https://discord.com/developers/docs/interactions/slash-commands#applicationcommandpermissions
```suggestion
 * https://discord.com/developers/docs/interactions/slash-commands#application-command-permissions-object-application-command-permissions-structure
```

2021-07-19 00:47 UTC, monbrey commented on payloads/v9/channel.ts
> + * https://discord.com/developers/docs/interactions/message-components#buttons-button-styles
```suggestion
 * https://discord.com/developers/docs/interactions/message-components#button-object-button-styles
```

2021-07-19 12:48 UTC, SpaceEEC requested changes
I only have these nits and a comment, otherwise LGTM. 👀 
~~Although I didn't do throughout testing.~~

2021-07-19 12:48 UTC, SpaceEEC commented on payloads/v8/channel.ts
> +
I only looked at a few files, but it doesn't seem to look like there were empty lines like these.
```suggestion
```

2021-07-19 12:48 UTC, SpaceEEC commented on payloads/v8/channel.ts
> +
```suggestion
```

2021-07-19 12:48 UTC, SpaceEEC commented on payloads/v9/channel.ts
> +
```suggestion
```

2021-07-19 12:48 UTC, SpaceEEC commented on payloads/v9/channel.ts
> +
```suggestion
```

2021-07-19 19:00 UTC, merged