feat(Interactions): context menu items
discordjs/discord-api-types pull request #166
Opened 2021-07-22 11:23 UTC by advaith1

... contextybois? rightclickybois?

i wanted to split APIApplicationCommandInteractionData into a union of two interfaces, but the narrowing didn't want to work when I tested it, so I kept it as one interface

2021-07-28 10:32 UTC, vladfrangu commented
This needs yet another rebase 👀

2021-08-11 19:26 UTC, vladfrangu requested changes

2021-08-11 19:26 UTC, vladfrangu commented on payloads/v9/_interactions/applicationCommands.ts
> +enum ApplicationCommandType {
```suggestion
export const enum ApplicationCommandType {
```

2021-08-11 19:26 UTC, vladfrangu commented on payloads/v9/_interactions/applicationCommands.ts
> +export type APIApplicationCommandInteraction =
shouldn't this be a union of the previous ones (the context menu and chat input ones)?

2021-08-11 19:29 UTC, vladfrangu requested changes

2021-08-11 19:29 UTC, vladfrangu commented on rest/v9/interactions.ts
> +export type RESTPostAPIApplicationCommandsJSONBody = Omit<APIApplicationCommand, 'id' | 'application_id' | 'type'> &
This doesn't realize description is not needed for 2 of the 3 types

2021-08-13 09:18 UTC, didinele approved these changes
Other than the attachment below, LGTM ![](https://sucks-to-b.eu/GeyvGC.png)

2021-08-13 10:21 UTC, didinele approved these changes

2021-08-13 10:27 UTC, vladfrangu requested changes

2021-08-13 10:27 UTC, vladfrangu commented on payloads/v9/_interactions/_applicationCommands/contextMenu.ts
> +	APIBaseApplicationCommandInteractionData,
Uuu... don't think we should have this exported

2021-08-13 10:27 UTC, vladfrangu commented on payloads/v9/_interactions/_applicationCommands/contextMenu.ts
> +import type { APIUser } from '../../index';
Point to users

2021-08-14 17:58 UTC, vladfrangu approved these changes

2021-08-14 17:58 UTC, merged