feat: Add role icons
discordjs/discord-api-types pull request #204
Opened 2021-09-22 00:55 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Adds support for role icons.

**Reference Discord API Docs PRs or commits:**
- https://github.com/discordjs/discord-api-types/pull/87

2021-09-28 07:33 UTC, kyranet requested changes

2021-09-28 07:33 UTC, kyranet commented on rest/v9/guild.ts
> +	 * the role's icon image (if the guild has the `ROLE_ICONS` feature)
```suggestion
	 * The role's icon image (if the guild has the `ROLE_ICONS` feature)
```

2021-09-28 07:33 UTC, kyranet commented on rest/v9/guild.ts
> +	 * the role's unicode emoji (if the guild has the `ROLE_ICONS` feature)
```suggestion
	 * The role's unicode emoji (if the guild has the `ROLE_ICONS` feature)
```

2021-09-28 07:33 UTC, kyranet commented on rest/v9/guild.ts
> +	 * @default null
```suggestion
	 * The role's unicode emoji (if the guild has the `ROLE_ICONS` feature)
```

2021-09-28 07:33 UTC, kyranet commented on rest/v9/guild.ts
> +	 * @default null
```suggestion
	 * The role's icon image (if the guild has the `ROLE_ICONS` feature)
```

2021-09-28 08:50 UTC, vladfrangu requested changes
Also v8 this :)

2021-09-28 08:50 UTC, vladfrangu commented on payloads/v9/guild.ts
> +	RoleIcons = 'ROLE_ICONS',
Please sort this alphabetically

2021-10-01 06:28 UTC, vladfrangu approved these changes

2021-10-01 06:29 UTC, merged