feat(APIGuildMember): Add per guild avatars
discordjs/discord-api-types pull request #208
Opened 2021-09-27 19:08 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

**Reference Discord API Docs PRs or commits:**
- https://github.com/discord/discord-api-docs/pull/3081

2021-09-28 07:28 UTC, kyranet approved these changes

2021-09-28 07:30 UTC, vladfrangu requested changes

2021-09-28 07:30 UTC, vladfrangu commented on payloads/v8/guild.ts
> +	avatar?: string;
Why is this one not nullable too?

2021-10-02 11:44 UTC, iCrawl approved these changes

2021-10-02 12:27 UTC, vladfrangu requested changes

2021-10-02 12:27 UTC, vladfrangu commented on payloads/v8/guild.ts
> +	 * the member's guild avatar hash
```suggestion
	 * The member's guild avatar hash
```

2021-10-03 13:15 UTC, vladfrangu approved these changes

2021-10-03 13:15 UTC, merged