feat: channel banners
discordjs/discord-api-types pull request #232
Opened 2021-11-08 20:36 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

**Reference Discord API Docs PRs or commits:**
- https://github.com/discord/discord-api-docs/pull/4068

2021-12-21 12:40 UTC, vladfrangu requested changes

2021-12-21 12:40 UTC, vladfrangu commented on deno/payloads/v8/guild.ts
>  }
Please sort features alphabetically

2022-01-19 13:59 UTC, vladfrangu commented
This needs a rebaseeeee 🎵

2022-01-19 22:37 UTC, vladfrangu approved these changes
Make sure rest types include these

2022-01-20 01:54 UTC, advaith1 commented
Channel banners were removed and guilds no longer have the feature.

2022-01-20 02:25 UTC, closed without merging