feat(APIApplication): app authorization links and tags
discordjs/discord-api-types pull request #239
Opened 2021-11-18 00:11 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

**Reference Discord API Docs PRs or commits:**
- https://github.com/discord/discord-api-docs/pull/4112

2021-11-18 00:14 UTC, ImRodry commented on deno/payloads/v8/application.ts
> +	tags?: [string, string, string, string, string];
Only 1 tag is required if specified
```suggestion
	tags?: [string, string?, string?, string?, string?];
```

2021-11-18 10:22 UTC, almeidx commented on deno/payloads/v8/application.ts
> +	scopes: string[];
Could this type be used instead?
https://github.com/discordjs/discord-api-types/blob/fa54b9de5522b9fa9d5367650950f8b0e44f6e14/payloads/v9/oauth2.ts#L5

2021-11-22 19:23 UTC, vladfrangu requested changes

2021-11-22 19:23 UTC, vladfrangu commented on payloads/v9/application.ts
> +	permissions: string;
Use the Permissions type

2021-11-22 19:32 UTC, vladfrangu requested changes

2021-11-22 19:32 UTC, vladfrangu commented on payloads/v8/application.ts
> +import type { OAuth2Scopes } from './index';
can you import it from its actual file instead, or consolidate all other imports from this one?

2021-11-22 19:56 UTC, vladfrangu approved these changes

2021-11-24 16:59 UTC, kyranet approved these changes

2022-02-15 19:24 UTC, vladfrangu commented
This needs a rebase

2022-03-18 17:48 UTC, popeda97 commented
suneettipirneni:feat/app-auth

2022-03-29 18:27 UTC, merged