feat: add support for user guild member read oauth2 scope and route
discordjs/discord-api-types pull request #254
Opened 2021-12-06 01:13 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

**Reference Discord API Docs PRs or commits:**
- https://github.com/discord/discord-api-docs/pull/4204

2021-12-06 08:04 UTC, vladfrangu approved these changes

2021-12-06 09:46 UTC, advaith1 commented
the response type should be added to rest/users

2021-12-06 19:57 UTC, kyranet approved these changes

2021-12-07 19:40 UTC, suneettipirneni commented
Upstream PR landed

2021-12-07 19:56 UTC, vladfrangu requested changes

2021-12-07 19:56 UTC, vladfrangu commented on payloads/v8/oauth2.ts
> +	GuildMembersRead = 'guilds.members.read',
Name this as the scope (`GuildsMembersRead`)

2021-12-07 20:20 UTC, vladfrangu approved these changes

2021-12-07 20:25 UTC, merged