feat(RESTJSONErrorCodes): add error 50086
discordjs/discord-api-types pull request #286
Opened 2022-01-03 04:01 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

**Reference Discord API Docs PRs or commits:**
- https://github.com/discord/discord-api-docs/pull/4302

2022-01-03 08:06 UTC, vladfrangu approved these changes

2022-01-03 09:06 UTC, kyranet approved these changes

2022-01-10 09:55 UTC, SpaceEEC approved these changes

2022-01-19 18:39 UTC, suneettipirneni commented
upstream PR merged

2022-01-19 19:08 UTC, vladfrangu commented
Flag was renamed, please update accordingly

2022-01-19 19:31 UTC, vladfrangu requested changes

2022-01-19 19:31 UTC, vladfrangu commented on deno/rest/common.ts
> +	CommunityServerChannelMustBeTextChannel,
Channels*

2022-01-19 19:31 UTC, almeidx requested changes
To mirror the docs text

2022-01-19 19:31 UTC, almeidx commented on deno/rest/common.ts
> +	CommunityServerChannelMustBeTextChannel,
```suggestion
	CommunityServerChannelsMustBeTextChannels,
```

2022-01-19 19:31 UTC, almeidx commented on rest/common.ts
> +	CommunityServerChannelMustBeTextChannel,
```suggestion
	CommunityServerChannelsMustBeTextChannels,
```

2022-01-19 19:34 UTC, vladfrangu approved these changes

2022-01-19 19:34 UTC, merged