fix(Autocomplete): Make options field required for autocomplete interaction
discordjs/discord-api-types pull request #332
Opened 2022-02-14 20:26 UTC by andre4ik3

**Please describe the changes this PR makes and why it should be merged:**
- Makes the `options` field required for autocomplete interactions
- Even though it is technically "optional" in the docs, in practice it will always be there when receiving an interaction
- The whole point of an autocomplete interaction is that a user is typing out an option. Therefore autocomplete interaction cannot be sent without options.

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- [Interaction Object Data Structure](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data-structure)

2022-02-14 20:34 UTC, andre4ik3 commented
Uh oh, I think there is issue with the test

2022-02-14 20:39 UTC, andre4ik3 commented
Not sure if there is a better way to do this, I never used type testing before

2022-02-15 01:31 UTC, vladfrangu requested changes

2022-02-15 01:31 UTC, vladfrangu commented on tests/v9/interactions.test-d.ts
> +			Required<Pick<APIChatInputApplicationCommandInteractionData, 'options'>>
APIApplicationCommandAutocompleteInteraction['data']

2022-02-15 05:12 UTC, andre4ik3 commented on tests/v9/interactions.test-d.ts
> +			Required<Pick<APIChatInputApplicationCommandInteractionData, 'options'>>
Awesome

2022-02-15 13:14 UTC, vladfrangu approved these changes

2022-02-15 13:15 UTC, merged