feat(interactions): add interaction localization
discordjs/discord-api-types pull request #370
Opened 2022-03-17 00:33 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/pull/4653

2022-03-17 00:39 UTC, vladfrangu requested changes
Also make sure rest types work fine with this

2022-03-17 00:39 UTC, vladfrangu commented on deno/payloads/v10/_interactions/_applicationCommands/_chatInput/base.ts
> +	name_localizations?: Record<LocaleString, string>;
All of these should be Partial'd (as not all locales have to be defined/are defined)

2022-03-17 11:35 UTC, vladfrangu approved these changes

2022-03-23 18:30 UTC, suneettipirneni commented
Upstream PR landed

2022-03-23 23:03 UTC, vladfrangu approved these changes

2022-03-23 23:04 UTC, merged