refactor(FormattingPatterns): remove `UserWithNickname`
discordjs/discord-api-types pull request #392
Opened 2022-04-01 17:24 UTC by vitorlops

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/commit/a8f7638e79391bb70e15996d1d88488a3b6364b2

2022-04-01 17:50 UTC, Jiralite requested changes
Please remove `UserWithOptionalNickname` which is below what you removed.

2022-04-04 14:01 UTC, vladfrangu commented
Honestly I'd just mark these 2 as deprecated instead and keep them for now (till we're 100% sure Discord stops using `!` in mentions

2022-04-04 14:10 UTC, vitorlops commented
Alright, I agree.

2022-04-04 14:55 UTC, vladfrangu requested changes

2022-04-04 14:55 UTC, vladfrangu commented on deno/globals.ts
> +	 * @deprecated `!` is no longer supported in mentions
```suggestion
	 * @deprecated Passing `!` in user mentions is no longer necessary / supported, and future message contents will not have it. 
```

2022-04-04 15:14 UTC, vitorlops commented on deno/globals.ts
> +	 * @deprecated `!` is no longer supported in mentions
Just changed "will not" for "won't".

2022-04-04 15:14 UTC, vladfrangu approved these changes

2022-04-04 15:21 UTC, merged