feat(APIGuildMember): add `flags`
discordjs/discord-api-types pull request #393
Opened 2022-04-01 20:38 UTC by vitorlops

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/pull/4737

2022-04-01 20:41 UTC, vladfrangu requested changes

2022-04-01 20:41 UTC, vladfrangu commented on deno/payloads/v10/guild.ts
> +	DID_REJOIN = 1 << 0,
Please correct the enum key names to be PascalCase as the rest of the enums

2022-04-04 15:00 UTC, kyranet approved these changes

2022-04-04 15:33 UTC, vitorlops commented
Closing. Upstream PR was closed.

2022-04-04 15:33 UTC, closed without merging