chore: make navbar consistent with other djs sites
discordjs/discord-api-types pull request #452
Opened 2022-05-26 20:07 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Before:

<img width="560" alt="Screen Shot 2022-05-26 at 4 03 25 PM" src="https://user-images.githubusercontent.com/77477100/170570113-cfc0cf33-4661-470a-93ef-40797599d0da.png">

After:

<img width="505" alt="Screen Shot 2022-05-26 at 4 02 49 PM" src="https://user-images.githubusercontent.com/77477100/170570380-8f6cb7aa-418a-421f-98f9-766944438ec1.png">

2022-05-26 20:09 UTC, vladfrangu requested changes

2022-05-26 20:24 UTC, vladfrangu commented on website/.prettierignore
> +# Versioned json
at the top level file too

2022-05-27 04:53 UTC, advaith1 commented on website/docusaurus.config.js
> +						label: 'discord api types',
```suggestion
						label: 'discord-api-types',
```

2022-05-27 10:32 UTC, vladfrangu approved these changes

2022-05-27 10:46 UTC, merged