feat: add `ConnectionService` to `APIConnection#type`
discordjs/discord-api-types pull request #491
Opened 2022-06-12 14:52 UTC by vvito7

**Please describe the changes this PR makes and why it should be merged:**
Makes `APIConnection#type` more precise by adding `ConnectionService` enum.

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/pull/5053

2022-06-12 19:05 UTC, vladfrangu requested changes

2022-06-12 19:05 UTC, vladfrangu commented on deno/payloads/v10/user.ts
> +	Youtube = 'youtube',
```suggestion
	YouTube = 'youtube',
```

2022-06-12 19:05 UTC, vladfrangu commented on deno/payloads/v10/user.ts
> +	PlaystationNetwork = 'playstation',
```suggestion
	PlayStationNetwork = 'playstation',
```

2022-06-12 19:05 UTC, vladfrangu commented on deno/payloads/v10/user.ts
> +	Github = 'github',
```suggestion
	GitHub = 'github',
```

2022-06-19 09:42 UTC, vladfrangu approved these changes

2022-06-24 08:34 UTC, kyranet approved these changes

2022-07-15 20:47 UTC, merged