chore(UserFlags): add `@unstable` to `Spammer` flag
discordjs/discord-api-types pull request #500
Opened 2022-06-19 22:12 UTC by Mateo-tem

**Please describe the changes this PR makes and why it should be merged:**

Adds `@unstable` to the `Spammer` user flag.
This idea comes from #495, which adds `Quarantined` user flag. Both of them are not documented by Discord.

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

2022-06-19 22:13 UTC, vladfrangu requested changes

2022-06-19 22:13 UTC, vladfrangu commented on deno/payloads/v10/user.ts
> +	 * @unstable This user flag is currently not documented by Discord but has known values which we will try to keep up to date.
```suggestion
	 * @unstable This user flag is currently not documented by Discord but has a known value which we will try to keep up to date.
```

2022-06-19 22:17 UTC, Mateo-tem commented on deno/payloads/v10/user.ts
> +	 * @unstable This user flag is currently not documented by Discord but has known values which we will try to keep up to date.
Done!

2022-06-20 07:05 UTC, vladfrangu commented
Can you also fix the prettier fail? 🙏

2022-06-20 22:46 UTC, vladfrangu approved these changes

2022-06-20 22:46 UTC, merged