feat(APIGuildForumChannel): update and add missing features
discordjs/discord-api-types pull request #575
Opened 2022-08-29 22:17 UTC by Mateo-tem

**Please describe the changes this PR makes and why it should be merged:**
- https://github.com/discord/discord-api-docs/pull/5391
(I've made a project of this before, just I need to replace some descriptions of the docs)

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

2022-08-31 00:10 UTC, vladfrangu requested changes

2022-08-31 01:13 UTC, Mateo-tem commented on deno/rest/v10/channel.ts
> +	available_tags?: APIGuildForumTag[];
What do you mean?

2022-08-31 09:32 UTC, vvito7 commented on deno/rest/common.ts
> +	WebhooksPostedToForumChannelsCannotHaveBothAThreadNameOrThreadId,
```suggestion
	WebhooksPostedToForumChannelsCannotHaveBothAThreadNameAndThreadId,
```

2022-08-31 11:00 UTC, vladfrangu commented on deno/rest/v10/channel.ts
> +	available_tags?: APIGuildForumTag[];
Well thats the rest route. I was asking is available_tags requires the id property of GuildForumTag or not

2022-08-31 12:27 UTC, Mateo-tem commented on deno/rest/v10/channel.ts
> +	available_tags?: APIGuildForumTag[];
In the docs says that `available_tags` in the rest route are just "an array of tag objects", so I think yes, it needs the `id` property (correct me if I'm wrong).

2022-08-31 12:28 UTC, vladfrangu commented on deno/rest/v10/channel.ts
> +	available_tags?: APIGuildForumTag[];
Well you can't have an ID if you're just creating the tags 😕 
Might have to ask in the docs repo

2022-08-31 15:24 UTC, vladfrangu commented on deno/rest/v10/channel.ts
> +	available_tags?: APIGuildForumTag[];
Just asked, this is fine as is!

2022-08-31 15:38 UTC, vladfrangu commented
Per discussing with devs:

- In RESTPostAPIGuildChannelsJSONBody or w/e:
  - `default_thread_rate_limit ` can also be set (once https://github.com/discord/discord-api-docs/issues/5400 is resolved)
  - reaction and tags can also be set on create
- In RESTPatchAPIGuildChannelJSONBody:
  - Please add a documentation warning for the tags properties that the id is *optional* when creating new tags (so they can set it to "0")

2022-08-31 23:34 UTC, Mateo-tem commented
> * In RESTPatchAPIGuildChannelJSONBody:
>   
>   * Please add a documentation warning for the tags properties that the id is _optional_ when creating new tags (so they can set it to "0")

I've tried making a `PATCH` request to edit a forum channel and only the `name` property is required for new tags. Then, the id will be generated automatically and will be returned in the `available_tags` property along with the tag objects in the payload (the new forum channel).

2022-09-11 02:37 UTC, Mateo-tem commented
> * In RESTPatchAPIGuildChannelJSONBody:
>   
>   * Please add a documentation warning for the tags properties that the id is _optional_ when creating new tags (so they can set it to "0")

- https://github.com/discord/discord-api-docs/pull/5458

2022-09-17 18:28 UTC, almeidx commented
Can you add this as well?
- discord/discord-api-docs#5475

2022-09-19 18:02 UTC, almeidx commented
Needs some updates to reflect the changes made in
- discord/discord-api-docs#5475

2022-09-20 20:08 UTC, almeidx commented
And again!
- https://github.com/discord/discord-api-docs/pull/5480

Maybe just revert the default_sort_order changes so this PR doesn't get blocked for the rest of eternity?

2022-09-25 17:21 UTC, vladfrangu approved these changes

2022-09-25 17:21 UTC, merged