chore(Types): update for PR discord/discord-api-docs#1886
discordjs/discord-api-types pull request #6
Opened 2020-09-07 10:58 UTC by vladfrangu

PR: https://github.com/discord/discord-api-docs/pull/1886/

2020-09-07 14:49 UTC, kyranet requested changes
You missed one field, `revoked`.

2020-09-07 14:49 UTC, kyranet commented on v6/payloads/guild.ts
> +	application?: APIGuildIntegrationApplication;
```suggestion
	subscriber_count: number;
	revoked: boolean;
	application?: APIGuildIntegrationApplication;
```

2020-09-07 15:23 UTC, kyranet approved these changes

2020-09-08 12:27 UTC, iCrawl approved these changes

2020-09-09 22:36 UTC, merged