feat(RESTGetAPICurrentUserGuildsQuery): add `with_counts`
discordjs/discord-api-types pull request #641
Opened 2022-11-12 15:40 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- discord/discord-api-docs#5628

2022-12-14 21:22 UTC, vladfrangu approved these changes

2022-12-14 22:47 UTC, kyranet approved these changes

2023-02-21 23:33 UTC, vladfrangu requested changes

2023-02-21 23:33 UTC, vladfrangu commented on deno/rest/v10/user.ts
>  export interface RESTAPIPartialCurrentUserGuild {
you need to add the approximate fields to these interfaces!

2023-02-23 23:28 UTC, vladfrangu approved these changes

2023-03-22 18:36 UTC, merged