feat(rpc): add *RPCCommands and RPCEvents*
discordjs/discord-api-types pull request #645
Opened 2022-11-17 15:25 UTC by TrueXPixells

**Please describe the changes this PR makes and why it should be merged:**
i added more rpc commands and events
Note: after /* */ comments are not including discord rpc docs

2022-11-18 09:57 UTC, vladfrangu requested changes

2022-11-18 09:57 UTC, vladfrangu commented on deno/rpc/common.ts
> +	DISPATCH = 'DISPATCH',
These need to follow the structure of other enums (so PascalCase for the name)

2022-11-18 09:57 UTC, vladfrangu commented on deno/rpc/common.ts
> +	/* https://github.com/discordjs/RPC/blob/master/src/constants.js#L14 */
Probably would help to either
1. get this documented on discord
2. Label this as unstable (see other examples in the module)

2022-11-18 09:57 UTC, vladfrangu commented on deno/rpc/common.ts
> +	READY = 'READY',
Ditto

2022-11-18 10:10 UTC, TrueXPixells commented
hmm, im sorry i dont know how to fix pascalcase cuz other enums are same
repo named;
RPCErrorCodes
RPCCloseEventCodes

my named;
RPCCommands
RPCEvents

i dont know what i do

2022-11-18 11:30 UTC, vladfrangu commented
> hmm, im sorry i dont know how to fix pascalcase cuz other enums are same repo named; RPCErrorCodes RPCCloseEventCodes
> 
> my named; RPCCommands RPCEvents
> 
> i dont know what i do

Not the name of the enum itself, the property names of the enum (so Ready not READY, etc)

2022-12-02 12:43 UTC, vladfrangu approved these changes

2022-12-08 20:07 UTC, TrueXPixells commented
yo @vladfrangu its been long days ago... please can u merge this PR? i deleting unused repos, please....

2025-02-25 08:21 UTC, Jiralite commented
Superseded by #1200.

2025-02-25 08:21 UTC, closed without merging