feat: add role connections
discordjs/discord-api-types pull request #651
Opened 2022-11-22 01:02 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- discord/discord-api-docs#5668

2022-11-22 08:41 UTC, vladfrangu requested changes

2022-11-22 08:41 UTC, vladfrangu commented on deno/payloads/v10/user.ts
> +export interface ApplicationRoleConnection {
Ditto

2022-12-02 12:39 UTC, vladfrangu requested changes

2022-12-02 12:39 UTC, vladfrangu commented on deno/payloads/v10/application.ts
> +	IntegerGreatThanOrEqual,
I'd call this `GreaterThan` not `GreatThan`

2022-12-02 12:39 UTC, vladfrangu commented on deno/payloads/v10/application.ts
> +	DatetimeGreatThanOrEqual,
Ditto

2022-12-14 18:27 UTC, almeidx commented on deno/payloads/v10/application.ts
> +	BooleanNotEqual,
They match the ones on discords end
![image](https://user-images.githubusercontent.com/42935195/207678081-497ffe17-89be-49e7-86f3-7eeec438827c.png)
https://discord.com/developers/docs/resources/application-role-connection-metadata#application-role-connection-metadata-object-application-role-connection-metadata-type

2022-12-14 21:18 UTC, vladfrangu approved these changes

2022-12-14 21:18 UTC, merged