fix(APIPartialChannel): name is nullable
discordjs/discord-api-types pull request #666
Opened 2022-12-10 15:27 UTC by cyyynthia

**Please describe the changes this PR makes and why it should be merged:**
Types incorrectly assume PartialChannel objects will always have a name In some circumstances, PartialChannels may be DM channels, which do have a null name.

Also fixes the comment about minimum name length.

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
This change aligns with the already documented [Channel data structure](https://discord.com/developers/docs/resources/channel#channel-object-channel-structure)

2022-12-10 19:12 UTC, vladfrangu commented
Can you apply it to the other channel types to make name non-nullable 🙏

2022-12-10 20:38 UTC, cyyynthia commented
Done, I've made the Guild/DM channel types more specific regarding whether their `name` is nullable or not. DM channels have it always `null`, GroupDM inherit the generic type (`string | null`), guild channels have it always `string`

2022-12-10 23:32 UTC, vladfrangu commented
Just so we're safe there's no regressions, can you add some tests too please? 🥺

2022-12-11 00:12 UTC, cyyynthia commented
> can you add some tests too please?

Done, I've only tested the `name` property though

2022-12-11 00:19 UTC, cyyynthia commented
I'm quite unsure as to why the CI build is failing telling me I didn't build the Deno types, `npm run build:deno` does 0 changes and the job's logs seem weird considering the changes I've made.. bad check script, or an oopsie on my end? 🤔

2022-12-11 10:47 UTC, vladfrangu requested changes

2022-12-11 10:47 UTC, vladfrangu commented on deno/payloads/v10/channel.ts
> +	name?: string;
Guild channels will always have a name

2022-12-11 10:47 UTC, vladfrangu commented on deno/payloads/v10/channel.ts
> +	 * The name of the channel (always null for DM channels)
Is it always returned as null or can it be undefined too? If it can't be undefined, drop the `?`

2022-12-11 13:20 UTC, cyyynthia commented
oof, GitHub's re-request thing dropped the other reviewers 💀

2022-12-11 20:47 UTC, vladfrangu approved these changes

2022-12-11 20:48 UTC, merged