feat(GatewayDispatchEvents): add `AuditLogEntryCreate`
discordjs/discord-api-types pull request #692
Opened 2023-01-12 22:09 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- discord/discord-api-docs#5849

2023-01-12 23:59 UTC, vladfrangu commented
You should also add the GUILD_BANS renamed intent in this PR

2023-01-21 15:54 UTC, Jiralite commented on gateway/v10.ts
> +export type GatewayAuditLogEntryCreateDispatchData = APIAuditLogEntry;
Isn't this missing `guild_id`?

2023-01-22 19:55 UTC, vladfrangu requested changes

2023-01-22 19:55 UTC, vladfrangu commented on deno/gateway/v10.ts
> +	/**
This should be done in the same structure as other deprecated renames

2023-01-23 22:33 UTC, vladfrangu approved these changes

2023-01-23 22:33 UTC, merged