feat(APIApplication): approx guild count and get self application endpoint
discordjs/discord-api-types pull request #728
Opened 2023-03-02 14:28 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- discord/discord-api-docs#5971

2023-03-02 14:40 UTC, Jiralite commented on deno/payloads/v10/application.ts
> +	 * An approximate count of the bots guild membership
```suggestion
	 * An approximate count of the bot's guild membership
```

2023-03-02 14:40 UTC, Jiralite commented on deno/payloads/v9/application.ts
> +	 * An approximate count of the bots guild membership
```suggestion
	 * An approximate count of the bot's guild membership
```

2023-03-02 14:40 UTC, Jiralite commented on payloads/v10/application.ts
> +	 * An approximate count of the bots guild membership
```suggestion
	 * An approximate count of the bot's guild membership
```

2023-03-02 14:40 UTC, Jiralite commented on payloads/v9/application.ts
> +	 * An approximate count of the bots guild membership
```suggestion
	 * An approximate count of the bot's guild membership
```

2023-06-15 12:34 UTC, vladfrangu commented
this needs a mega rebase

2023-07-14 01:13 UTC, Jiralite approved these changes

2023-07-16 23:06 UTC, vladfrangu requested changes

2023-07-16 23:06 UTC, vladfrangu commented on deno/rest/v10/mod.ts
> +	currentApplication() {
Where's RESTGetCurrentApplicationResult 👀

2023-07-17 12:26 UTC, vladfrangu approved these changes

2023-07-17 12:26 UTC, merged