feat: add `VoiceChannelEffectSend` event
discordjs/discord-api-types pull request #739
Opened 2023-03-28 08:32 UTC by advaith1

**Please describe the changes this PR makes and why it should be merged:**
Adds the VoiceChannelEffectSend gateway event

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
* https://github.com/discord/discord-api-docs/pull/6025

2023-03-28 08:35 UTC, vladfrangu submitted a review, later dismissed

2023-03-28 08:35 UTC, vladfrangu commented on deno/gateway/v10.ts
> +	PREMIUM,
We don't do screaming enums here

2024-08-15 21:37 UTC, almeidx requested changes

2024-08-15 21:37 UTC, almeidx commented on gateway/v10.ts
> +	sound_override_path?: string | null;
Not documented. Either mark as `@unstable` (if this is still included in the payload) or just get rid of it

2024-08-15 21:37 UTC, almeidx commented on gateway/v10.ts
> +	 * See https://discord.com/developers/docs/topics/gateway-events#voice-channel-effect-send-animation-types
```suggestion
```

2024-08-15 21:37 UTC, almeidx commented on gateway/v10.ts
> +export enum VoiceChannelEffectSendAnimationType {
```suggestion
/**
  * https://discord.com/developers/docs/topics/gateway-events#voice-channel-effect-send-animation-types
  */
export enum VoiceChannelEffectSendAnimationType {
```

2024-09-22 14:43 UTC, almeidx approved these changes

2024-09-23 11:15 UTC, merged