feat(AutoModeration): add blocking words in member profile
discordjs/discord-api-types pull request #740
Opened 2023-04-01 14:41 UTC by jaw0r3k

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

- https://github.com/discord/discord-api-docs/pull/6040/files

2024-05-31 16:12 UTC, almeidx requested changes
CI is also failing

2024-05-31 16:12 UTC, almeidx commented on payloads/v10/autoModeration.ts
> +	 * Check if member profile contains words from a user defined list of keywords
```suggestion
	 * Check if member profile contains words from a user defined list of keywords (Maximum of 1 per guild)
```

2024-06-03 11:07 UTC, almeidx approved these changes

2024-06-03 11:08 UTC, vladfrangu approved these changes

2024-06-03 11:09 UTC, merged