feat: add support for super reactions
discordjs/discord-api-types pull request #744
Opened 2023-04-06 20:24 UTC by Mateo-tem

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

- https://github.com/discord/discord-api-docs/pull/6056

2023-04-06 20:25 UTC, vladfrangu requested changes

2023-04-06 20:25 UTC, vladfrangu commented on deno/payloads/v10/channel.ts
> +export interface ReactionCountDetails {
Prefix with API

2023-04-07 10:38 UTC, vladfrangu submitted a review, later dismissed

2023-05-20 07:36 UTC, JJRcop commented
MESSAGE_REACTION_ADD also has updates, which aren't in this PR. Is this usable yet or still subject to changes?

<details>
<summary>Screenshots</summary>

![Screenshot_20230520_103159](https://github.com/discordjs/discord-api-types/assets/5211576/b177dba0-7985-4cf9-b3af-105bdd2a4507)

![Screenshot_20230520_102004](https://github.com/discordjs/discord-api-types/assets/5211576/a8ed20f5-2688-4beb-b90c-fdfe5ebdeaa5)
</details>

2023-05-20 07:44 UTC, Syjalo commented
We only add what is documented (or will be documented). Suggest changes in the docs PR.
- https://github.com/discord/discord-api-docs/pull/6056

2023-05-20 07:45 UTC, JJRcop commented
Ah, I misplaced the repo this was on, thanks.

2023-08-24 20:43 UTC, almeidx requested changes
The `APIReaction` interface is missing the `me_burst` property, and some of the descriptions are outdated

2023-08-24 23:49 UTC, vladfrangu submitted a review, later dismissed

2023-08-24 23:49 UTC, vladfrangu commented on deno/rest/v10/channel.ts
> +	type: number;
Should be turned into an enum

2024-02-21 10:41 UTC, Jiralite commented
Hey @Mateo-tem, are you able to split this pull request up so we have something to merge?

2024-02-22 00:09 UTC, Mateo-tem commented
> Hey @Mateo-tem, are you able to split this pull request up so we have something to merge?

Yes! I'll do that in a moment 🫡

2024-02-22 02:42 UTC, Jiralite requested changes

2024-02-22 02:42 UTC, Jiralite commented on deno/payloads/v10/channel.ts
> +	 * HEX colors used for super reaction
```suggestion
	 * Hexadecimal colors used for this super reaction
```

2024-02-22 02:42 UTC, Jiralite commented on deno/payloads/v9/channel.ts
> +	 * HEX colors used for super reaction
```suggestion
	 * Hexadecimal colors used for this super reaction
```

2024-02-22 02:42 UTC, Jiralite commented on payloads/v10/channel.ts
> +	 * HEX colors used for super reaction
```suggestion
	 * Hexadecimal colors used for this super reaction
```

2024-02-22 02:42 UTC, Jiralite commented on payloads/v9/channel.ts
> +	 * HEX colors used for super reaction
```suggestion
	 * Hexadecimal colors used for this super reaction
```

2024-02-22 02:42 UTC, Jiralite commented on deno/payloads/v10/channel.ts
> +	 * Reaction count details object
This description just echoes the name of the interface, like it's as useful as not including it. Let's improve it:

```suggestion
	 * An object detailing the individual reaction counts for different types of reactions 
```

2024-02-22 02:42 UTC, Jiralite commented on deno/payloads/v9/channel.ts
> +	 * Reaction count details object
This description just echoes the name of the interface, like it's as useful as not including it. Let's improve it:

```suggestion
	 * An object detailing the individual reaction counts for different types of reactions 
```

2024-02-22 02:42 UTC, Jiralite commented on payloads/v10/channel.ts
> +	 * Reaction count details object
This description just echoes the name of the interface, like it's as useful as not including it. Let's improve it:

```suggestion
	 * An object detailing the individual reaction counts for different types of reactions 
```

2024-02-22 02:42 UTC, Jiralite commented on payloads/v9/channel.ts
> +	 * Reaction count details object
This description just echoes the name of the interface, like it's as useful as not including it. Let's improve it:

```suggestion
	 * An object detailing the individual reaction counts for different types of reactions 
```

2024-02-23 00:15 UTC, almeidx approved these changes

2024-02-23 00:16 UTC, merged