feat: implement FormatPatterns
discordjs/discord-api-types pull request #79
Opened 2021-01-31 18:00 UTC by Fyko

This PR creates a common object of message formats as regexes.
https://discord.com/developers/docs/reference#message-formatting-formats

2021-01-31 18:05 UTC, vladfrangu requested changes

2021-01-31 18:05 UTC, vladfrangu commented on common/index.ts
> +	User: /<@!?(\d{17,19})>/,
Should contain the 3 possibilities we'd want - User, user w nick and user with optional nick

2021-01-31 18:05 UTC, vladfrangu commented on common/index.ts
> +	Emoji: /<?(a)?:?(\w{2,32}):(\d{17,19})>?/,
Please split this into 3 (non animated, only animated, both)

2021-01-31 18:05 UTC, vladfrangu commented on common/index.ts
> +};
cast as const

2021-01-31 18:49 UTC, vladfrangu requested changes

2021-01-31 18:49 UTC, vladfrangu commented on common/index.ts
> +	StaticEmoji: /<:(\w{2,32}):(\d{17,19})>?/,
Include the d.js one with the match groups

2021-01-31 23:25 UTC, vaporox commented on common/index.ts
> +	StaticEmoji: /<:(\w{2,32}):(\d{17,19})>?/,
```suggestion
	Emoji: /<(a)?:(\w{2,32}):(\d{17,19})>/,
	AnimatedEmoji: /<(a):(\w{2,32}):(\d{17,19})>/,
	StaticEmoji: /<:(\w{2,32}):(\d{17,19})>/,
```
those aren't optional for the other mention patterns either

2021-02-01 00:11 UTC, vladfrangu requested changes

2021-02-01 00:11 UTC, vladfrangu commented on common/index.ts
> +	User: /<@(\d{17,19})>/,
add docs for what each represent :3

2021-02-02 22:25 UTC, vladfrangu approved these changes

2021-02-02 22:26 UTC, merged