feat: Application patch and new properties
discordjs/discord-api-types pull request #810
Opened 2023-08-22 10:58 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**

- https://github.com/discord/discord-api-docs/pull/6297

2023-09-28 19:02 UTC, vladfrangu submitted a review, later dismissed

2023-09-28 22:12 UTC, almeidx requested changes

2023-09-28 22:12 UTC, almeidx commented on rest/v10/application.ts
> +export type RESTPatchCurrentApplicationJSONBody = StrictPartial<
Missing `flags`

2023-09-28 22:12 UTC, almeidx commented on payloads/v10/application.ts
> +	 * An approximate count of the app's guild membership
This description is slightly misleading, can you update it to the new one

2023-09-28 22:19 UTC, almeidx approved these changes

2023-10-03 18:26 UTC, vladfrangu approved these changes

2023-10-03 18:30 UTC, suneettipirneni approved these changes

2023-10-03 18:34 UTC, merged