fix(RESTPatchAPIChannelJSONBody): add missing `applied_tags` field
discordjs/discord-api-types pull request #828
Opened 2023-09-23 21:13 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

2023-09-23 21:36 UTC, vladfrangu requested changes

2023-09-23 21:36 UTC, vladfrangu commented on deno/rest/v10/channel.ts
> +	 * the IDs of the set of tags that have been applied to a thread in a
Start with capitalized word

2023-09-23 21:50 UTC, vladfrangu submitted a review, later dismissed

2023-09-23 21:52 UTC, almeidx requested changes

2023-09-23 21:52 UTC, almeidx commented on rest/v9/channel.ts
> +	 * GUILD_FORUM or a GUILD_MEDIA channel; limited to 5
```suggestion
	 * The ids of the set of tags that have been applied to a thread-only channel; limited to 5
```

2023-09-23 21:52 UTC, almeidx commented on rest/v10/channel.ts
> +	 * GUILD_FORUM or a GUILD_MEDIA channel; limited to 5
```suggestion
	 * The ids of the set of tags that have been applied to a thread-only channel; limited to 5
```

2023-09-23 21:52 UTC, almeidx commented on deno/rest/v9/channel.ts
> +	 * GUILD_FORUM or a GUILD_MEDIA channel; limited to 5
```suggestion
	 * The ids of the set of tags that have been applied to a thread-only channel; limited to 5
```

2023-09-23 21:52 UTC, almeidx commented on deno/rest/v10/channel.ts
> +	 * GUILD_FORUM or a GUILD_MEDIA channel; limited to 5
```suggestion
	 * The ids of the set of tags that have been applied to a thread-only channel; limited to 5
```

2023-09-23 22:12 UTC, almeidx approved these changes

2023-09-23 22:23 UTC, vladfrangu approved these changes

2023-09-25 10:50 UTC, HeadTriXz approved these changes
LGTM

2023-09-25 11:22 UTC, Jiralite approved these changes

2023-09-25 11:23 UTC, merged