feat(APIInteraction): DM slash commands and property descriptions
discordjs/discord-api-types pull request #84
Opened 2021-02-09 22:48 UTC by advaith1

https://github.com/discord/discord-api-docs/pull/2568

client update is out

2021-02-09 22:59 UTC, vladfrangu requested changes

2021-02-09 22:59 UTC, vladfrangu commented on v8/payloads/interactions.ts
> +export interface APIBaseInteraction {
Missed link

2021-02-09 22:59 UTC, vladfrangu commented on v8/payloads/interactions.ts
> +	 * read-only property, always `1`
Every start of tsdocs start capitalized

2021-02-09 22:59 UTC, vladfrangu commented on v8/payloads/interactions.ts
> +	 * the guild it was sent from
```suggestion
	 * The guild it was sent from
	 *
	 * In the case of an `APIDMInteraction`, this will not be present
```

2021-02-10 01:04 UTC, advaith1 commented
docs pr has been merged

2021-02-10 08:34 UTC, vladfrangu approved these changes
LGTM, will test union when I get home

2021-03-15 22:50 UTC, merged