fix(GatewayGuildDeleteDispatchData): make unavailable optional
discordjs/discord-api-types pull request #862
Opened 2023-12-28 07:05 UTC by Saghetti0

The `unavailable` field in `GatewayGuildDeleteDispatchData` can be undefined, but in the API types, it's marked as always present. Even though the [documentation](https://discord.com/developers/docs/topics/gateway-events#guild-delete) specifies that it's an unavailable guild, and the example object has the field present, it says that the field can be not set:

>  If the `unavailable` field is not set, the user was removed from the guild.

I also confirmed this with some of my own testing. I added and then kicked a bot from a guild, and got a guild delete event without the `unavailable` field. One thing I'm not sure about though is if the optional should be on `APIUnavailableGuild` instead of the dispatch, as the docs are vague on the details.

2023-12-28 08:47 UTC, vladfrangu requested changes

2023-12-28 08:47 UTC, vladfrangu commented on deno/gateway/v10.ts
> +export type GatewayGuildDeleteDispatchData = Omit<APIUnavailableGuild, 'unavailable'> &
Lets make this its own interface

2024-07-02 20:13 UTC, almeidx approved these changes

2024-09-05 19:52 UTC, almeidx commented
Superseded by #1092

2024-09-05 19:52 UTC, closed without merging