types(CDNRoutes): use generics for `format` options
discordjs/discord-api-types pull request #868
Opened 2024-01-31 23:51 UTC by TAEMBO

**Please describe the changes this PR makes and why it should be merged:**
Implements generics for `format` options. This removes the cumbersome template literal union typings that are returned, and allows those using CDNRoutes to more easily understand what's returned from a given route function. Retains strict boundaries for what extensions are allowed to be used for a given route.

close #866

2024-01-31 23:52 UTC, vladfrangu submitted a review, later dismissed

2024-02-01 00:33 UTC, sdanialraza commented
Discussed this internally, you don't need to prefix the type parameters with T, so just `Format` or `Index` should be good

2024-02-01 07:20 UTC, vladfrangu requested changes

2024-02-01 07:20 UTC, vladfrangu commented on deno/rest/v10/mod.ts
>  	 *
Need to also apply this to storePageAsset

2024-02-01 20:35 UTC, vladfrangu submitted a review, later dismissed

2024-02-01 20:51 UTC, almeidx submitted a review, later dismissed

2024-02-01 21:02 UTC, vladfrangu approved these changes

2024-02-01 21:37 UTC, almeidx approved these changes

2024-02-05 12:19 UTC, merged