feat: add type query param for get reactions endpoint
discordjs/discord-api-types pull request #879
Opened 2024-02-22 00:20 UTC by Mateo-tem

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**

- https://github.com/discord/discord-api-docs/pull/6377

2024-05-16 19:36 UTC, almeidx requested changes

2024-05-16 19:36 UTC, almeidx commented on rest/v10/channel.ts
> +	type: ReactionType;
This is optional

2024-05-17 00:03 UTC, Jiralite commented on deno/rest/v10/channel.ts
> +	 * The reaction type (0 for normal and 1 for super)
I would recommend removing the information in the brackets—it's already in `ReactionType`. It's not really good for future-proofing if and when more types are added... it'll just be a longer comment which is still explained by the type.

2024-05-22 08:25 UTC, almeidx approved these changes

2024-05-22 10:04 UTC, vladfrangu approved these changes

2024-05-22 10:04 UTC, merged