feat: bot banners
discordjs/discord-api-types pull request #906
Opened 2024-03-16 12:54 UTC by jaw0r3k

**Please describe the changes this PR makes and why it should be merged:**

**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:**
- https://github.com/discord/discord-api-docs/pull/6710

2024-03-16 12:57 UTC, almeidx requested changes

2024-03-16 12:57 UTC, almeidx commented on rest/v8/user.ts
Please revert the changes to the v8 files as we're no longer updating them (check this interface's tsdoc)

2024-03-16 15:20 UTC, kyranet approved these changes

2024-03-31 18:24 UTC, merged

2024-03-31 18:24 UTC, vladfrangu commented
Merging this as is, as it's been officially announced in DDevs